name: zcap_net_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  window_size: ^0.1.0
  http: ^1.4.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.15
  package_info_plus: ^8.3.0
  connectivity_plus: ^5.0.2
  dropdown_search: ^5.0.3
  data_table_2: ^2.5.8
  easy_localization: ^3.0.1
  flutter_treeview: ^1.0.6
  url_launcher: ^6.2.5
  animated_tree_view: ^2.3.0

  cupertino_icons: ^1.0.2
  
  provider: ^6.1.2
  crypto: ^3.0.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/translations/
    - assets/config/config.json