
--/*** START: DROP TABLES

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcapDetails' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE zcapDetails
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcapDetailTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE zcapDetailTypes
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'detailTypeCategories' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE detailTypeCategories
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dataTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE dataTypes
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcaps' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE zcaps
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'entities' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE entities
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'entityTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE entityTypes
	END
GO
IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'buildingTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
		DROP TABLE buildingTypes
	END
GO
----/*** END: DROP TABLES

--/*** START: BUILDINGTYPES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'buildingTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE buildingTypes (
	[buildingTypeId]	BIGINT	IDENTITY(1,1) PRIMARY KEY,
	[name]				NVARCHAR(255)	NOT NULL,
    [startDate]			DATE NOT NULL,
    [endDate]			DATE NULL,
    [createdAt]			DATETIME NOT NULL,
    [updatedAt]			DATETIME NOT NULL
)
	END
GO
--/*** END: BUILDINGTYPES ***/

--/*** START: ENTITYTYPES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'entityTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE entityTypes (
	[entityTypeId]		BIGINT	IDENTITY(1,1) PRIMARY KEY,
	[name]				NVARCHAR(255)	NOT NULL,
    [startDate]			DATE NOT NULL,
    [endDate]			DATE NULL,
    [createdAt]			DATETIME NOT NULL,
    [updatedAt]			DATETIME NOT NULL
)
	END
GO
--/*** END: ENTITYTYPES ***/

--/*** START: ENTITIES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'entities' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE entities (
	[entityId]			BIGINT				IDENTITY(1,1) PRIMARY KEY,
	[name]				NVARCHAR(255)	NOT NULL,
	[entityTypeId]		BIGINT				NOT NULL REFERENCES entityTypes(entityTypeId),
	[email]				NVARCHAR(255)	NULL,
	[phone1]			NVARCHAR(100)	NOT NULL,
	[phone2]			NVARCHAR(100)	NULL,
    [startDate]			DATE NOT NULL,
    [endDate]			DATE NULL,
    [createdAt]			DATETIME NOT NULL,
    [updatedAt]			DATETIME NOT NULL
)
	END
GO
--/*** END: ENTITIES ***/

--/*** START: ZCAPS ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcaps' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE zcaps (
	[zcapId]			BIGINT				IDENTITY(1,1) PRIMARY KEY,
	[name]				NVARCHAR(255)	NOT NULL,
	[buildingTypeId]	BIGINT			NOT NULL REFERENCES buildingTypes(buildingTypeId),
	[address]			NVARCHAR(500)	NOT NULL,
	[treeRecordId]		BIGINT			NULL REFERENCES tree(treeRecordId),
	[latitude]			REAL			NULL,
	[longitude]			REAL			NULL,
	[entityId]			BIGINT			NOT NULL REFERENCES entities(entityId),
    [startDate]			DATE			NOT NULL,
    [endDate]			DATE			NULL,
    [createdAt]			DATETIME		NOT NULL,
    [updatedAt]			DATETIME		NOT NULL
)
	END
GO
--/*** END: ZCAPS ***/

--/*** START: DATATYPES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dataTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE dataTypes (
	[dataTypeId]	BIGINT IDENTITY(1,1) PRIMARY KEY,
	[name]			NVARCHAR(255)
)
	END
GO
--/*** END: DATATYPES ***/

--/*** START: DETAILTYPECATEGORIES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'detailTypeCategories' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE detailTypeCategories (
	[detailTypeCategoryId]	BIGINT	IDENTITY(1,1) PRIMARY KEY,
	[name]					NVARCHAR(255)	NOT NULL,
    [startDate]				DATE NOT NULL,
    [endDate]				DATE NULL,
    [createdAt]				DATETIME NOT NULL,
    [updatedAt]				DATETIME NOT NULL
)
	END
GO
--/*** END: DETAILTYPECATEGORIES ***/

--/*** START: ZCAPDETAILTYPES ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcapDetailTypes' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE zcapDetailTypes (
	[zcapDetailTypeId]		BIGINT				IDENTITY(1,1) PRIMARY KEY,
	[name]					NVARCHAR(255)	NOT NULL,
	[detailTypeCategoryId]	BIGINT			NOT NULL REFERENCES detailTypeCategories(detailTypeCategoryId),
	[dataTypeId]			BIGINT				NOT NULL REFERENCES dataTypes(dataTypeId),
	[isMandatory]			BIT				NOT NULL,
    [startDate]				DATE NOT NULL,
    [endDate]				DATE NULL,
    [createdAt]				DATETIME NOT NULL,
    [updatedAt]				DATETIME NOT NULL
)
	END
GO

--/*** END: ZCAPDETAILTYPES ***/

--/*** START: ZCAPDETAILS ***/
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'zcapDetails' and [TABLE_TYPE] = 'BASE TABLE')
	BEGIN
CREATE TABLE zcapDetails (
	[zcapDetailId]		BIGINT				IDENTITY(1,1) PRIMARY KEY,
	[zcapId]			BIGINT				NOT NULL REFERENCES zcaps(zcapId),
	[zcapDetailTypeId]	BIGINT				NOT NULL REFERENCES zcapDetailTypes(zcapDetailTypeId),
	[value]				NVARCHAR(MAX)	NOT NULL,
    [startDate]			DATE NOT NULL,
    [endDate]			DATE NULL,
    [createdAt]			DATETIME NOT NULL,
    [updatedAt]			DATETIME NOT NULL)
	END
GO
--/*** END: ZCAPDETAILS ***/
